name = "culturallyai"
compatibility_date = "2024-09-25"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Environment variables
# Add your Supabase URL and anon key here (public values, not secrets)
# These PUBLIC_ prefixed vars are exposed to the client-side code
[vars]
SUPABASE_URL = "https://kjdnwalzuawushnsvkbm.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZG53YWx6dWF3dXNobnN2a2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NDY3NzEsImV4cCI6MjA3NzIyMjc3MX0.Rp8XguA-JoEPA2NBOpXhMhw0-jkDCK8hrOkmOcZdP8o"
PUBLIC_SUPABASE_URL = "https://buqdkyvrnwwotbaxseze.supabase.co"
PUBLIC_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cWRreXZybnd3b3RiYXhzZXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5Mzc1ODUsImV4cCI6MjA3NzUxMzU4NX0.TLrp73QJeousCqhDuB0wLZ8fUVuLcejxfjhN_6ghkO4"
